#!/bin/bash

#target=c11node10
target=10.5.147.210
file=$1
ram=$2
vcpu=$3
telnetport=$4
vncport=$5
listenport=$6
postcopy=$7
speed=$8
#speed=125
#speed=30
background=off
#background=on
#mac=$3

# prepare incoming migration at target
# start vm
ssh $target /root/qemu/listen-daemon $file $ram $vcpu $telnetport $vncport $listenport 

#if [ $file == "master.qcow2" ]; then
#	telnetport=4436
#fi

# migrate
nc localhost $telnetport << EOF
migrate_set_capability postcopy $postcopy
migrate_set_capability postcopy-move-background $background
migrate_set_speed $speed
migrate tcp:$target:$listenport
EOF
echo

#info version
#info kvm

#sleep 5

# stop vm
#nc localhost $telnetport << EOF
#info migrate
#info status
#EOF
#echo

#quit
#info migrate_capabilities
