#!/bin/bash

telnetport=4436
nc localhost $telnetport << EOF
info status
info version
info kvm
migrate_set_capatility postcopy on
migrate tcp:c11node10:4444
EOF
echo

sleep 5

nc localhost 4446 << EOF
info migrate
info status
quit
EOF
echo

#info migrate_capabilities
