#!/bin/bash

nodes=( master slave1 slave2 )
telnetport=4436
#listenport=$2
#mac=$3

# prepare incoming migration at target
# start vm
#ssh $target /root/qemu/listen-postcopy-daemon $listenport $mac

# migrate
fun migrate() {
nc localhost $telnetport << EOF
info status
info version
info kvm
migrate_set_capability postcopy on
migrate tcp:c11node10:4444
EOF
echo
}

#info migrate_capabilities

# stop vm
fun info() {
nc localhost $telnetport << EOF
info migrate
info status
EOF
echo
}

fun stopvm() {
nc localhost $telnetport << EOF
quit
EOF
echo
}

# check info periodically
#sleep 10
