#!/bin/bash
# basic controller with slow start phase

# base dir
homedir=/root
basedir=$homedir/exp
#basedir=/home/tsugawa/controller

nexthost=null
if [ $HOSTNAME == "c11node7" ]; then
	nexthost=c11node9
elif [ $HOSTNAME == "c11node8" ]; then
	nexthost=c11node10
fi

sampletime=$1

# maximum number of concurrent vms
max=14

# maximum link capacity in MB/s
maxbw=118

# initial window (number of vms) to migrate
#cwnd=1
cwnd=$2
total_cwnd=0
cfile=/tmp/cwnd

# threshold
thresh=8

#alpha=0.9
alpha=0.75

# phase: ss (slow start), ca (congestion avoidance, aimd)
#phase=ss
phase=$3

epsilon=0
#epsilon=0.1
saturated=0

# monitor throughput
prev_thruput=0
total_time=0

# number of vms running
#prefix=$HOSTNAME-
prefix=vm512-

rvms=`virsh list | grep running | grep $prefix | wc -l`
#echo rvms $rvms
#rvms0=$rvms
tmplog=/tmp/exptime

echo sampletime $sampletime cwnd $cwnd phase $phase

echo $cwnd > $cfile

#$homedir/vmanage/migrator &

while [ $rvms -gt 0 ]
do
        comp=`echo "$rvms < $cwnd" | bc -l`
	echo rvms $rvms cwnd $cwnd comp $comp
        if [ $comp -eq 1 ]; then
                cwnd=$rvms
		echo $cwnd > $cfile
		# transfer the rest VMs to next host
		vms0=`expr $cwnd - $rvms`
		if [ $vms0 -eq 0 ]; then
			vms0=1
		fi
#		if [ $nexthost != "null" ]; then
#			ssh $nexthost $basedir/controller/runcontroller 20 $sampletime 2 $vms0 $phase &
 #       	fi
	fi

        echo rvms $rvms cwnd ${cwnd/.*} $cwnd
        #echo rvms $rvms cwnd ${cwnd/.*} $cwnd `date +%T.%N | cut -c1-12`

	# yk = bandwidth usage
        thruput=`dstat -n --noupdate --noheaders $sampletime 1 | tail -1 | awk '{print $2}' | sed 's/B//g;s/M/000000/g;s/k/000/g'`
	thruput=`echo "$thruput / $cwnd" | bc -l`
	thruput=${thruput/.*}

        total_cwnd=`expr $total_cwnd "+" $cwnd`
        #echo summary $cwnd $t $thruput $total_cwnd $total_time

	# rk = y(k-1)
	# rk = (1-c)*rk + c*yk
	# ek = yk - rk
        # if 0.1*rk < delta increase +1
        # else if delta < -0.1*rk decrease -1
        delta=`echo "$thruput - $prev_thruput" | bc -l`
        echo summary $cwnd $thruput $delta
        comp=`echo "$delta < -$epsilon * $prev_thruput" | bc -l`
        #comp2=`echo "$delta > $epsilon * $prev_thruput" | bc -l`

        # not saturated
        if [ $saturated == 0 ]; then
                # congestion occurs
                if [ $comp -eq 1 ]; then
                        cwnd=`echo "$cwnd * $alpha" | bc -l`
                        #cwnd=`echo "$cwnd - 1" | bc -l`
                        cwnd=${cwnd/.*}
                        saturated=1
                        thresh=$cwnd
                else # no congestion
                        if [ $phase == ss ]; then
                                #echo slow start
                                cwnd=`expr $cwnd "*" 2`
                        else
                                #echo congestion avoidance
                                cwnd=`expr $cwnd "+" 1`
                        fi
                fi
        else # saturated
                cwnd=`expr $cwnd "+" 1`
                # set the state as not-saturated
                saturated=0
        fi

        if [ $cwnd -ge $thresh ]; then
                phase=ca
        fi

        # non-positive
        comp=`expr $cwnd "<" 1`
        #if [ $cwnd -lt 1 ]; then
        if [ $comp -eq 1 ]; then
                cwnd=1
        fi

        #overbooked
        comp=`expr $cwnd ">" $max`
        if [ $comp -eq 1 ]; then
                cwnd=$max
        fi
	
	echo -n $cwnd > $cfile

        prev_thruput=$thruput

        rvms=`virsh list | grep running | grep $prefix | wc -l`
#       echo rvms $rvms

done

# total summary
# [total number of vms] [total time] [total throughput]
#total_cwnd=`expr $rvms0 "-" $rvms`
#comp=`echo "$total_time == 0" | bc -l`

#if [ $comp -eq 1 ]; then
#        total_thruput=0
#else
#        total_thruput=`echo "3600 * $total_cwnd / $total_time" | bc -l`
#fi

echo total_summary \#$total_cwnd $total_time $total_thruput

#wait
