#!/bin/bash
scheds=( lf )
#scheds=( sf lf rand )
vwnds=( 1 )
#vwnds=( 30 10 5 1 )
#rounds=( 3 4 )
#delays=( 20-80-180 )
delays=( 80 )
sleeptime=300
#sleeptime=1
#network=dynamic
network=static

basedir=/nfs/vmanage/controller
exe=$basedir/multiplecontroller.py
#exe=$basedir/multiple-without-controller.py

wanem=gr122

function exp(){
	host=gr121
	local cmd
	local sched=$1
	local vwnd=$2
	local delay=$3
	local run=$4
#	exe=$basedir/multiple-without-controller.py
	logdir=$basedir/log/$delay
	logfile=$logdir/$sched-$vwnd-r$run

	mkdir -p $logdir

	if [ $network == "dynamic" ]; then
		echo "$basedir/congestor &"
		#$basedir/congestor &
	fi
	
	cmd="logsave $logfile time -p $exe -s $sched -v $vwnd"
	if [ -n "$5" ]; then
		echo "not empty"
		cmd="ssh $5 $cmd"
	else
		echo "empty"
	fi
	
	echo $cmd
	$cmd

	wait
}

for delay in ${delays[@]}
do
	d=`expr $delay / 2`
	ssh $wanem service tc delay $d

	for sched in ${scheds[@]}
	do
		for vwnd in ${vwnds[@]}
		do
			cmd="exp $sched $vwnd $delay"
			#cmdssh="expssh $sched $vwnd $delay"
		#	if [ $vwnd == 0 ]; then
		#		cmd="/nfs/vmanage/startcontroller $cpm $delay"
		#	fi	

			echo $cmd 1
			$cmd 1
			sleep $sleeptime

			echo $cmd 2 gr121
			$cmd 2 gr121
#			sleep $sleeptime

#			$cmd 3 
			#sleep $sleeptime

			#ssh gr121 $cmd 4
			#sleep $sleeptime
		done	
	done
	ssh $wanem service tc stop
done

function expssh(){
	local sched=$1
	local vwnd=$2
	local delay=$3
	local run=$4
	host=gr121
	logfile=$basedir/log/$delay/$sched-$vwnd-r$run

	if [ $network == "dynamic" ]; then
		echo "$basedir/congestor &"
		#$basedir/congestor &
	fi
	
	cmd="logsave $logfile time -p $exe -s $sched -v $vwnd"
	cmd="ssh $host $cmd"
	#cmd="ssh $host logsave $logfile time -p $exe -s $sched -v $vwnd"
	echo $cmd
	#$cmd
	#ssh $host logsave $logfile time -p $exe $cpms $vwnd

	wait
}

