#!/bin/bash
scheds=( lf sf rand )
#scheds=( 1 2 4 8 )
vmss=( 1 5 10 30 )
#vmss=( 0 1 2 4 8 )
rounds=( 1 2 )
#rounds=( 1 2 3 4)

rm avg.dat
rm total.dat

for sched in ${scheds[@]}
do
	pconcur=${sched}.dat

#	if [ $sched -eq 1 ]; then 
#		pconcur=${sched}pm.dat
#	fi
	>$pconcur

	rm ${sched}.avg
	rm ${sched}.total

	for vms in ${vmss[@]}
	do
		# all rounds
		vfile=$sched-$vms.fin
		avgfile=$sched-$vms.avg
		rm $vfile
		rm $avgfile

		# average
		vconcur=$sched-$vms.concur
		avgavg=$sched-$vms.avgavg
		rm $vconcur
		rm $avgavg
		
		vtotal=$sched-$vms.total
		rm $vtotal

		for round in ${rounds[@]}
		do
			file=$sched-$vms-r$round

			# total
			grep real $file | awk '{print $2}' >> $vtotal
	
			# finish
			grep finish $file | awk  '{print $NF}' | sed 's/ //g' > $file.fin
			#grep finish $file | awk  '{print $NF}' | sed '1d' | sed 's/ //g' > $file.fin
			grep finish $file | awk  '{print $2}' | sed 's/ //g' > $file.avg
			#grep finish $file | awk  '{print $2}' | sed '1d' | sed 's/ //g' > $file.avg
			# merge
			pr -m -t -s\  $vfile $file.fin | gawk '{print }' > /tmp/merged
			cp /tmp/merged $vfile
			pr -m -t -s\  $avgfile $file.avg | gawk '{print }' > /tmp/merged_avg
			cp /tmp/merged_avg $avgfile
		done

		# average
		awk 'NF {s=0; for(i=1;i<=NF;i++) s+=$i;printf("%.2f\n", s/NF)}' $vfile > $vconcur	
		awk 'NF {s=0; for(i=1;i<=NF;i++) s+=$i;printf("%.2f\n", s/NF)}' $avgfile > $avgavg	

		# merge
		pr -m -t -s\  $pconcur $vconcur > /tmp/concur
		cp /tmp/concur $pconcur
	
		# average rows
		awk '{sum+=$1}END{print sum/NR}' $avgavg >> ${sched}.avg

		#total average rows
		awk '{sum+=$1}END{print sum/NR}' $vtotal >> ${sched}.total
		
	done
	
	cat ${sched}.avg >> avg.dat
	cat ${sched}.total >> total.dat
	# transpose
#	sed -r '1{s/$/ /;s/ / \n/g};:a;$!N;s/$/ /;:b;s/\n(.*\n+)(\S+\s)/\2@!@\1/;tb;s/@!@/\n/g;${s/ \n/\n/g;s/\n+$//;q};ba' ${sched}sched.avg >> avg.dat
#	sed -r '1{s/$/ /;s/ / \n/g};:a;$!N;s/$/ /;:b;s/\n(.*\n+)(\S+\s)/\2@!@\1/;tb;s/@!@/\n/g;${s/ \n/\n/g;s/\n+$//;q};ba' ${sched}sched.total >> total.dat
done
