#!/bin/bash
#pool window size
NUM_PMs=8
pwnd=1
vwnd=1

sampletime=1
avgprev=0
totalprev=0
rvms=64
alpha=0.5

#function getBandwidth(){
getBandwidth(){
	local total=0
#	for (( i = 1; i <= $pwnd; i++))
#	do
#		host=gra$i
#	done

	bw=`rocks run host "dstat -n -N eth1 $sampletime 1 | tail -1" | awk '{print $2}' | sed 's/B//g;s/M/000000/g;s/k/000/g' ` 
	
	echo $bw > /tmp/total_bandwidth
	awk 'NF {s=0; for(i=1;i<=NF;i++) s+=$i;printf("%.0f\n", s)}' /tmp/total_bandwidth

	#echo $bw
}

function getRVMs(){
	rvms=`rocks run host "virsh list" | grep running | wc -l`
	echo $rvms
}

echo rvms, total, avg, pwnd, vwnd, totalvms

getRVMs

while (( rvms > 0 ))
do
	#for (( i = 1; i < pwnd; i++))
	#do
	#done

	total=`getBandwidth`
	avg=$(( total / vwnd ))
	totalvms=$(( pwnd * vwnd ))
	
	echo $rvms, $total, $avg, $pwnd, $vwnd, $totalvms

	if (( avg < avgprev )); then
		vwnd=$(( vwnd - 1 ))
		#vwnd=$(( vwnd * alpha ))
	else
		vwnd=$(( vwnd + 1 ))
	fi

	if (( total < totalprev )); then
		pwnd=$(( pwnd - 1 ))
		#vwnd=$(( vwnd * alpha ))
	else
		pwnd=$(( pwnd + 1 ))
	fi

	#if (( vwnd < NUM_PMs )); then
	#	pwnd=$vwnd
	#else
#		pwnd=$NUM_PMs
#	fi

	if (( vwnd < 1 )); then
		vwnd=1
	fi
	if (( pwnd < 1 )); then
		pwnd=1
	fi
	
	#rvms=$(( rvms - 1 ))
	totalprev=$total
	avgprev=$avg
	getRVMs
done
