#!/bin/bash
#output=ramsize
output=vcpu

#rams=( 256 512 1024 2048 4096 )
rams=( 1024 )
caps=( default xbzrle auto-converge xbzrle+auto-converge )
#caps=( xbzrle )
#caps=( default )
#dirtyrates=( 10 20 30 40 50 60 70 80 90 100 110 120 )
dirtyrates=( 0 )
vcpus=( 1 2 4 8 12 )
#speeds=( 50 60 70 80 90 100 110 120 )
speeds=( 125 )
expnos=( 1 )

#echo "# ram totaltime downtime" > $output
echo "# vcpu totaltime downtime totaldata throughput duplicate" > $output

for expno in ${expnos[@]}
do
for mem in ${rams[@]}
do
	ram=$mem
	#echo -n "$ram " >> $output
for sp in ${speeds[@]}
do
	speed=$sp
	for vcpu in ${vcpus[@]}
	do
		echo -n "$vcpu " >> $output
		#for rate in ${dirtyrates[@]}
		for cap in ${caps[@]}
		do
			datadir=vcpu${vcpu}/speed${speed}/$cap
			#datadir=ram${ram}/vcpu${vcpu}/speed${speed}/$cap
			datafile=$datadir/${expno}.log
			#datafile=$datadir/dirty${rate}_${expno}.log
			echo $datadir
			#cat $datafile 
			totaltime=`grep "total time:" $datafile | awk '{print $3}'`
			downtime=`grep "downtime:" $datafile | awk '{print $2}'`
			totaldata=`grep "transferred ram:" $datafile | awk '{print $3}'`
			throughput=`grep "throughput:" $datafile | awk '{print $2}'`
			duplicate=`grep "duplicate:" $datafile | awk '{print $2}'`
			#echo "$totaltime $downtime $totaldata $throughput $duplicate " >> $output
			echo -n "$totaltime $downtime $totaldata $throughput $duplicate " >> $output
		done
		echo >> $output
	done
	echo >> $output
done
done
	echo >> $output
done

cat $output
