#!/bin/bash

name=180ms
#name=20tmt
#name=demo
data=${name}.dat
script=${name}.R
png=${name}.png
emf=${name}.emf
eps=${name}.eps

function genscript() {
	cmd="emf($emf)"

	figure=$png

cat >$script << EOF
library(ggplot2)

#$cmd
png("$figure")
#postscript("plot.eps")
#require(devEMF)
#emf("plot.emf")

# header = TRUE ignores the first line, check.names = FALSE allows '+' in 'C++'
benchmark <- read.table("$data", header = TRUE, row.names = "vwnd", check.names = FALSE)

# 't()' is matrix tranposition, 'beside = TRUE' separates the benchmarks, 'heat' provides nice colors
barplot(t(as.matrix(benchmark)), beside = TRUE, col = heat.colors(4))

# 'cex' stands for 'character expansion', 'bty' for 'box type' (we don't want borders)
legend("topleft", names(benchmark), cex = 0.9, bty = "n", fill = heat.colors(4))

EOF

	R CMD BATCH $script
}

genscript

git add .
git commit -a -m $script
git push
